name: Docker CI-CD Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.IMAGE_NAME }}:latest
            ${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          
      - name: Install cloudflared
        run: |
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg \
            | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null

          echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] \
          https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" \
            | sudo tee /etc/apt/sources.list.d/cloudflared.list

          sudo apt-get update
          sudo apt-get install -y cloudflared

      - name: Setup SSH (Cloudflared)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          cat <<EOF > ~/.ssh/config
          Host my-server
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/id_rsa
            # Added service token headers below
            ProxyCommand cloudflared access ssh --hostname %h --header "CF-Access-Client-Id=${{ secrets.CF_ACCESS_CLIENT_ID }}" --header "CF-Access-Client-Secret=${{ secrets.CF_ACCESS_CLIENT_SECRET }}"
            StrictHostKeyChecking no
          EOF


      - name: Deploy on Server
        run: |
           ssh my-server "
            docker pull ${{ secrets.IMAGE_NAME }}:latest &&
            docker stop cicd-demo || true &&
            docker rm cicd-demo || true &&
            docker run -d \
              --name cicd-demo \
              --restart unless-stopped \
              -p 7777:8000 \
              ${{ secrets.IMAGE_NAME }}:latest"
